version: '3.8'

services:
  libro_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libro_reclamaciones_app
    ports:
      - "7001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - libro_db
    command: ["/entrypoint.sh"]
    networks:
      - nginx-proxy-manager_default

  libro_db:
    image: mysql:8.0
    container_name: libro_reclamaciones_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306"  # Asegura que no choque con otros contenedores
    volumes:
      - libro_db_data:/var/lib/mysql
    networks:
      - nginx-proxy-manager_default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: libro_reclamaciones_phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: libro_reclamaciones_db
      PMA_PORT: 3306
    networks:
      - nginx-proxy-manager_default

volumes:
  libro_db_data:

networks:
  nginx-proxy-manager_default:
    external: true
